### ISSUE TITLE
broken link at the end of Rmd

### ISSUE THREAD

**Issue by bdemeshev** [ShareStats/Statistics_Taxonomy#2]
https://github.com/ShareStats/Statistics_Taxonomy/blob/main/Statistics_Taxonomy.Rmd

The link in the end of file to sharestats.nl is broken, probably should start with https :smile_cat:

**Comment by ShKlinkenberg** [comment]
Thanks Boris

From: Boris Demeshev ***@***.***>
Date: Thursday, 16 September 2021 at 09:22
To: ShareStats/Statistics_Taxonomy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShareStats/Statistics_Taxonomy] broken link at the end of Rmd (#2)

https://github.com/ShareStats/Statistics_Taxonomy/blob/main/Statistics_Taxonomy.Rmd<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FShareStats%2FStatistics_Taxonomy%2Fblob%2Fmain%2FStatistics_Taxonomy.Rmd&data=04%7C01%7Cs.klinkenberg%40uva.nl%7C3035c699952145448c8b08d978e2c2ce%7Ca0f1cacd618c4403b94576fb3d6874e5%7C1%7C0%7C637673737622325608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U7qOGcRyxDF8fo2dtKvJ9qTf4SO2JHEb4Fso5fZl8UE%3D&reserved=0>

The link in the end of file to sharestats.nl is broken, probably should start with https 😸
