### ISSUE TITLE
txt or csv sources for reproducible science

### ISSUE THREAD

**Issue by bdemeshev** [ShareStats/Statistics_Taxonomy#3]
Just a proposal: csv or simple txt source files would be much better than xlsx source files.

**Comment by bdemeshev** [comment]
Sorry, I've missed the test yaml folder!

**Comment by ShKlinkenberg** [comment]
Hi, @bdemeshev 

The Yaml test is still a test. We are going to translate the taxonomy in xlsx so non tech peeps can do the job, afterwards we can convert to Yaml and txt etc :-)

**Comment by lindemann09** [comment]
> Just a proposal: csv or simple txt source files would be much better than xlsx source files.

Yes, I agree. I use a JSON file of the taxominie. See:  https://github.com/lindemann09/Statistics_Taxonomy/tree/main/json
